// src/components/Contact.tsx
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Mail, Linkedin, Github, MapPin, ChevronDown } from "lucide-react";
import { motion, AnimatePresence } from "motion/react";
import { useState, useEffect } from "react";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

const Contact = () => {
  const emails = [
    { address: "aaditya12raj@gmail.com", provider: "Gmail" },
    { address: "aaditya12raj@tuta.io", provider: "Tutanota" },
    { address: "InfiniteEcl1pse@protonmail.com", provider: "ProtonMail" }
  ];

  const [currentEmailIndex, setCurrentEmailIndex] = useState(0);

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentEmailIndex((prev) => (prev + 1) % emails.length);
    }, 3000);

    return () => clearInterval(interval);
  }, [emails.length]);

  return (
    <section id="contact" className="py-20 px-6 bg-muted/30">
      <div className="max-w-4xl mx-auto">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">Let's Connect</h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Ready to collaborate on innovative cybersecurity projects? 
            Let's discuss how we can build something secure and amazing together.
          </p>
        </div>

        <Card className="border-border/50 overflow-hidden">
          <CardContent className="p-8">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div className="space-y-6">
                <div>
                  <h3 className="text-xl font-semibold mb-4">Get in Touch</h3>
                  <p className="text-muted-foreground mb-6">
                    Whether you're looking for a cybersecurity analyst, network security specialist, or just want to chat about 
                    security technology, I'm always open to new opportunities and conversations.
                  </p>
                </div>

                <div className="space-y-4">
                  <div className="flex items-center space-x-3">
                    <MapPin className="h-5 w-5 text-highlight" />
                    <span className="text-muted-foreground">Lalitpur, Nepal</span>
                  </div>
                  <div className="flex items-center space-x-3">
                    <Mail className="h-5 w-5 text-highlight" />
                    <div className="relative overflow-hidden">
                      <AnimatePresence mode="wait">
                        <motion.a
                          key={currentEmailIndex}
                          href={`mailto:${emails[currentEmailIndex].address}`}
                          className="text-muted-foreground hover:text-foreground transition-colors block"
                          initial={{ opacity: 0, y: 20 }}
                          animate={{ opacity: 1, y: 0 }}
                          exit={{ opacity: 0, y: -20 }}
                          transition={{ duration: 0.5, ease: "easeInOut" }}
                        >
                          <span className="font-medium">{emails[currentEmailIndex].address}</span>
                          <span className="text-sm text-muted-foreground ml-2">({emails[currentEmailIndex].provider})</span>
                        </motion.a>
                      </AnimatePresence>
                    </div>
                  </div>
                </div>
              </div>

              <div className="space-y-6">
                <div>
                  <h3 className="text-xl font-semibold mb-4">Connect With Me</h3>
                  <div className="space-y-3">
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <Button variant="outline" className="w-full justify-start">
                          <Mail className="h-5 w-5 mr-3" />
                          Send Email
                          <ChevronDown className="h-3 w-3 ml-auto" />
                        </Button>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent align="start" className="w-full">
                        <DropdownMenuItem asChild>
                          <a 
                            href="mailto:aaditya12raj@gmail.com"
                            className="flex items-center space-x-2 w-full"
                          >
                            <Mail className="h-4 w-4" />
                            <span>Gmail</span>
                          </a>
                        </DropdownMenuItem>
                        <DropdownMenuItem asChild>
                          <a 
                            href="mailto:aaditya12raj@tuta.io"
                            className="flex items-center space-x-2 w-full"
                          >
                            <Mail className="h-4 w-4" />
                            <span>Tutanota</span>
                          </a>
                        </DropdownMenuItem>
                        <DropdownMenuItem asChild>
                          <a 
                            href="mailto:InfiniteEcl1pse@protonmail.com"
                            className="flex items-center space-x-2 w-full"
                          >
                            <Mail className="h-4 w-4" />
                            <span>ProtonMail</span>
                          </a>
                        </DropdownMenuItem>
                      </DropdownMenuContent>
                    </DropdownMenu>
                    
                    <Button variant="outline" className="w-full justify-start" asChild>
                      <a href="https://linkedin.com/in/aaditya-raj-390113324" target="_blank" rel="noopener noreferrer">
                        <Linkedin className="h-5 w-5 mr-3" />
                        LinkedIn Profile
                      </a>
                    </Button>
                    
                    <Button variant="outline" className="w-full justify-start" asChild>
                      <a href="https://github.com/KronosWasTaken" target="_blank" rel="noopener noreferrer">
                        <Github className="h-5 w-5 mr-3" />
                        GitHub Profile
                      </a>
                    </Button>
                  </div>
                </div>

                <div className="pt-4">
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <Button size="lg" className="w-full bg-highlight text-highlight-foreground hover:bg-highlight/90">
                        Get in Touch
                        <ChevronDown className="h-4 w-4 ml-2" />
                      </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="start" className="w-full">
                      <DropdownMenuItem asChild>
                        <a 
                          href="mailto:aaditya12raj@gmail.com"
                          className="flex items-center space-x-2 w-full"
                        >
                          <Mail className="h-4 w-4" />
                          <span>Gmail</span>
                        </a>
                      </DropdownMenuItem>
                      <DropdownMenuItem asChild>
                        <a 
                          href="mailto:aaditya12raj@tuta.io"
                          className="flex items-center space-x-2 w-full"
                        >
                          <Mail className="h-4 w-4" />
                          <span>Tutanota</span>
                        </a>
                      </DropdownMenuItem>
                      <DropdownMenuItem asChild>
                        <a 
                          href="mailto:InfiniteEcl1pse@protonmail.com"
                          className="flex items-center space-x-2 w-full"
                        >
                          <Mail className="h-4 w-4" />
                          <span>ProtonMail</span>
                        </a>
                      </DropdownMenuItem>
                    </DropdownMenuContent>
                  </DropdownMenu>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </section>
  );
};

export default Contact;

// src/lib/components/Contact.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { fly, fade } from "svelte/transition";
  import Card from "./ui/card.svelte";
  import CardContent from "./ui/card-content.svelte";
  import Button from "./ui/button.svelte";
  import { clickOutside } from "$lib/actions/clickOutside";
  import GithubIcon from '~icons/simple-icons/github';
  import LinkedinIcon from '~icons/simple-icons/linkedin';
  import MailIcon from '~icons/lucide/mail';
  import MapPinIcon from '~icons/lucide/map-pin';
  import ChevronDownIcon from '~icons/lucide/chevron-down';
  import { emails, socialLinks } from "$lib/data";

  let currentIndex = $state(0);
  let sendEmailOpen = $state(false);

  onMount(() => {
    const interval = setInterval(() => {
      currentIndex = (currentIndex + 1) % emails.length;
    }, 4000);
    return () => clearInterval(interval);
  });

  const handleSendEmailToggle = () => {
    sendEmailOpen = !sendEmailOpen;
  };
  const handleSendEmailClose = () => {
    sendEmailOpen = false;
  };
</script>

<section id="contact" class="py-20 px-6 bg-muted/30">
  <div class="max-w-4xl mx-auto">
    <div class="text-center mb-16">
      <h2 class="text-3xl md:text-4xl font-bold mb-4">Let's Connect</h2>
      <p class="text-lg text-muted-foreground max-w-2xl mx-auto">
        Ready to collaborate on innovative cybersecurity projects? Let's discuss
        how we can build something secure and amazing together.
      </p>
    </div>

    <Card class="border-border/50 overflow-hidden">
      <CardContent class="p-8">
        <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div class="space-y-6">
            <div>
              <h3
                class="text-xl font-semibold mb-4 text-highlight font-heading"
              >
                Get in Touch
              </h3>
              <p class="text-muted-foreground mb-6 leading-relaxed">
                Whether you're looking for a cybersecurity analyst, network
                security specialist, or just want to chat about security
                technology, I'm always open to new opportunities and
                conversations.
              </p>
            </div>
            <div class="space-y-4">
              <div class="flex items-center space-x-3">
                <MapPinIcon class="h-5 w-5 text-highlight" />
                <span class="text-muted-foreground font-medium"
                  >Lalitpur, Nepal</span
                >
              </div>
              <div class="flex items-center space-x-3">
                <MailIcon class="h-5 w-5 text-highlight shrink-0" />
                <div class="relative h-6 flex-1 overflow-hidden">
                  {#key currentIndex}
                    <div
                      in:fly={{ y: 20, duration: 500, delay: 200 }}
                      out:fly={{ y: -20, duration: 500 }}
                      class="absolute inset-0 flex items-center"
                    >
                      <a
                        href="mailto:{emails[currentIndex].address}"
                        class="text-foreground hover:text-highlight transition-all inline-flex items-center whitespace-nowrap"
                        aria-label="Email {emails[currentIndex].provider}"
                      >
                        <span class="font-semibold"
                          >{emails[currentIndex].address}</span
                        >
                        <span
                          class="text-xs px-2 py-0.5 rounded-full bg-highlight/10 text-highlight ml-2 border border-highlight/20"
                          >{emails[currentIndex].provider}</span
                        >
                      </a>
                    </div>
                  {/key}
                </div>
              </div>
            </div>
          </div>

          <div class="space-y-6">
            <div>
              <h3 class="text-xl font-semibold mb-4">Connect With Me</h3>
              <div class="space-y-3">
                <div class="relative" use:clickOutside={handleSendEmailClose}>
                  <Button
                    variant="outline"
                    class="w-full justify-start rounded-full hover:bg-accent hover:text-accent-foreground hover:border-accent transition-all"
                    aria-expanded={sendEmailOpen}
                    aria-haspopup="menu"
                    onclick={handleSendEmailToggle}
                  >
                    <MailIcon class="h-5 w-5 mr-3" />
                    Send Email
                    <ChevronDownIcon class="h-3 w-3 ml-auto" />
                  </Button>
                  {#if sendEmailOpen}
                    <div
                      role="menu"
                      class="absolute top-full left-0 z-50 mt-1 w-full rounded-md border bg-popover text-popover-foreground shadow-md p-1"
                    >
                      {#each emails as email}
                        <a
                          role="menuitem"
                          href="mailto:{email.address}"
                          class="flex items-center space-x-2 w-full rounded-sm px-2 py-1.5 text-sm hover:bg-accent hover:text-accent-foreground transition-colors"
                          onclick={handleSendEmailClose}
                          aria-label="Send email via {email.provider}"
                        >
                          <MailIcon class="h-4 w-4" />
                          <span>{email.provider}</span>
                        </a>
                      {/each}
                    </div>
                  {/if}
                </div>

                <Button
                  variant="outline"
                  class="w-full justify-start rounded-full hover:bg-accent hover:text-accent-foreground hover:border-accent transition-all"
                  href={socialLinks.linkedin}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <LinkedinIcon
                    width="20"
                    height="20"
                    class="mr-3"
                  />
                  LinkedIn Profile
                </Button>

                <Button
                  variant="outline"
                  class="w-full justify-start rounded-full hover:bg-accent hover:text-accent-foreground hover:border-accent transition-all"
                  href={socialLinks.github}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <GithubIcon
                    width="20"
                    height="20"
                    class="mr-3"
                  />
                  GitHub Profile
                </Button>
              </div>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  </div>
</section>
