// src/components/ParticleBackground.tsx
import React, { useEffect, useRef } from 'react';

interface Particle {
  x: number;
  y: number;
  vx: number;
  vy: number;
  size: number;
  opacity: number;
  baseOpacity: number;
  hue: number;
}

const ParticleBackground: React.FC = () => {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const mouseRef = useRef({ x: 0, y: 0 });
  const particlesRef = useRef<Particle[]>([]);
  const animationRef = useRef<number | undefined>(undefined);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const resizeCanvas = () => {
      canvas.width = window.innerWidth;
      canvas.height = window.innerHeight;
    };

    resizeCanvas();
    window.addEventListener('resize', resizeCanvas);

    const getIsDarkMode = () => {
      return document.documentElement.classList.contains('dark') ||
        (!document.documentElement.classList.contains('light') &&
          window.matchMedia('(prefers-color-scheme: dark)').matches);
    };

    let isDarkMode = getIsDarkMode();

    // Use MutationObserver instead of polling theme every frame
    const observer = new MutationObserver(() => {
      isDarkMode = getIsDarkMode();
    });
    observer.observe(document.documentElement, { attributes: true, attributeFilter: ['class'] });

    const initParticles = () => {
      const particles: Particle[] = [];
      const isMobile = window.innerWidth < 768 || /Android|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);
      const densityFactor = isMobile ? 20000 : 8000;
      const numParticles = Math.floor((canvas.width * canvas.height) / densityFactor);

      for (let i = 0; i < numParticles; i++) {
        const baseOpacity = Math.random() * 0.4 + 0.2;
        particles.push({
          x: Math.random() * canvas.width,
          y: Math.random() * canvas.height,
          vx: (Math.random() - 0.5) * 0.2,
          vy: (Math.random() - 0.5) * 0.2,
          size: Math.random() * 1.5 + 0.5,
          opacity: baseOpacity,
          baseOpacity,
          hue: 0,
        });
      }
      particlesRef.current = particles;
    };

    initParticles();

    const handleMouseMove = (e: MouseEvent) => {
      mouseRef.current = {
        x: e.clientX,
        y: e.clientY,
      };
    };

    const handleTouchMove = (e: TouchEvent) => {
      if (e.touches.length > 0) {
        mouseRef.current = {
          x: e.touches[0].clientX,
          y: e.touches[0].clientY,
        };
      }
    };

    window.addEventListener('mousemove', handleMouseMove);
    window.addEventListener('touchmove', handleTouchMove, { passive: true });

    let lastTime = 0;
    const targetFPS = window.innerWidth < 768 ? 30 : 60;
    const frameInterval = 1000 / targetFPS;

    const animate = (currentTime: number = 0) => {
      if (currentTime - lastTime < frameInterval) {
        animationRef.current = requestAnimationFrame(animate);
        return;
      }

      ctx.clearRect(0, 0, canvas.width, canvas.height);

      const particles = particlesRef.current;
      const mouseX = mouseRef.current.x;
      const mouseY = mouseRef.current.y;
      const pCount = particles.length;
      const linkDistance = 150;
      const mouseRadius = 200;
      const cellSize = linkDistance;
      const cols = Math.ceil(canvas.width / cellSize);
      const rows = Math.ceil(canvas.height / cellSize);
      const grid: Particle[][] = [];

      for (let i = 0; i < pCount; i++) {
        const p = particles[i];

        const dx = mouseX - p.x;
        const dy = mouseY - p.y;
        const distance = Math.sqrt(dx * dx + dy * dy);
        const maxDistance = 120;

        if (distance < maxDistance && distance > 0) {
          const force = (maxDistance - distance) / maxDistance * 0.01;
          const angle = Math.atan2(dy, dx);
          p.vx += Math.cos(angle) * force;
          p.vy += Math.sin(angle) * force;
          p.opacity = Math.min(p.baseOpacity * 2, 0.8);
        } else {
          p.opacity = p.baseOpacity;
        }

        p.vx += (Math.random() - 0.5) * 0.002;
        p.vy += (Math.random() - 0.5) * 0.002;
        p.vx *= 0.995;
        p.vy *= 0.995;
        p.x += p.vx;
        p.y += p.vy;

        if (p.x < 0) p.x = canvas.width;
        if (p.x > canvas.width) p.x = 0;
        if (p.y < 0) p.y = canvas.height;
        if (p.y > canvas.height) p.y = 0;

        ctx.beginPath();
        ctx.arc(p.x, p.y, p.size, 0, Math.PI * 2);
        ctx.fillStyle = isDarkMode ? `rgba(255, 255, 255, ${p.opacity})` : `rgba(60, 60, 60, ${p.opacity})`;
        ctx.fill();

        const col = (p.x / cellSize) | 0;
        const row = (p.y / cellSize) | 0;
        const idx = row * cols + col;
        if (idx >= 0 && idx < rows * cols) {
          if (!grid[idx]) grid[idx] = [];
          grid[idx].push(p);
        }
      }

      const linkDistSq = linkDistance * linkDistance;
      const mouseRadiusSq = mouseRadius * mouseRadius;

      for (let i = 0; i < pCount; i++) {
        const p1 = particles[i];
        const dxM = p1.x - mouseX;
        const dyM = p1.y - mouseY;
        const dMSq = dxM * dxM + dyM * dyM;

        if (dMSq < mouseRadiusSq) {
          const col = (p1.x / cellSize) | 0;
          const row = (p1.y / cellSize) | 0;

          for (let r = row - 1; r <= row + 1; r++) {
            if (r < 0 || r >= rows) continue;
            for (let c = col - 1; c <= col + 1; c++) {
              if (c < 0 || c >= cols) continue;

              const cellContent = grid[r * cols + c];
              if (!cellContent) continue;

              for (let j = 0; j < cellContent.length; j++) {
                const p2 = cellContent[j];
                if (p1 === p2) continue;

                const dx = p1.x - p2.x;
                const dy = p1.y - p2.y;
                const dSq = dx * dx + dy * dy;

                if (dSq < linkDistSq) {
                  const dM = Math.sqrt(dMSq);
                  const d = Math.sqrt(dSq);
                  const op = (1 - d / linkDistance) * (1 - dM / mouseRadius) * 0.5;

                  ctx.beginPath();
                  ctx.strokeStyle = isDarkMode ? `rgba(255, 255, 255, ${op})` : `rgba(60, 60, 60, ${op})`;
                  ctx.lineWidth = 0.8;
                  ctx.moveTo(p1.x, p1.y);
                  ctx.lineTo(p2.x, p2.y);
                  ctx.stroke();
                }
              }
            }
          }
        }
      }

      lastTime = currentTime;
      animationRef.current = requestAnimationFrame(animate);
    };

    const timer = setTimeout(() => {
      window.addEventListener('resize', resizeCanvas);
      resizeCanvas();
      initParticles();
      animate();
    }, 200);

    return () => {
      clearTimeout(timer);
      observer.disconnect();
      window.removeEventListener('resize', resizeCanvas);
      window.removeEventListener('mousemove', handleMouseMove);
      window.removeEventListener('touchmove', handleTouchMove);
      if (animationRef.current) {
        cancelAnimationFrame(animationRef.current);
      }
    };
  }, []);

  return (
    <canvas
      ref={canvasRef}
      className="absolute inset-0 pointer-events-none"
      style={{ zIndex: 2, background: 'transparent' }}
    />
  );
};

export default ParticleBackground;

// src/lib/components/ParticleBackground.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  interface Particle {
    x: number; y: number;
    vx: number; vy: number;
    size: number;
    near: boolean;
  }

  let canvas: HTMLCanvasElement;

  onMount(() => {
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const mouse = { x: -9999, y: -9999 };
    let particles: Particle[] = [];
    let animFrame: number;

    let width = 0;
    let height = 0;

    const resize = () => {
      width = window.innerWidth;
      height = window.innerHeight;
      canvas.width = width;
      canvas.height = height;
    };

    window.addEventListener('resize', () => { resize(); init(); });

    // Initial setup deferred to first frame to avoid forced reflow
    requestAnimationFrame(() => {
      resize();
      init();
      animate();
    });

    const isDark = () => document.documentElement.classList.contains('dark');
    let dark = isDark();
    const mo = new MutationObserver(() => { dark = isDark(); });
    mo.observe(document.documentElement, { attributes: true, attributeFilter: ['class'] });

    const init = () => {
      const count = Math.floor((width * height) / 10000);
      particles = Array.from({ length: count }, () => ({
        x: Math.random() * width,
        y: Math.random() * height,
        vx: (Math.random() - 0.5) * 0.2,
        vy: (Math.random() - 0.5) * 0.2,
        size: Math.random() * 1.5 + 0.5,
        near: false
      }));
    };

    const handleMouseMove = (e: MouseEvent) => { mouse.x = e.clientX; mouse.y = e.clientY; };
    const handleTouchMove = (e: TouchEvent) => {
      if (e.touches[0]) { mouse.x = e.touches[0].clientX; mouse.y = e.touches[0].clientY; }
    };
    window.addEventListener('mousemove', handleMouseMove);
    window.addEventListener('touchmove', handleTouchMove, { passive: true });

    const LINK_DIST = 150;
    const MOUSE_RAD = 200;
    const PUSH_RAD = 120;
    const LINK_DIST_SQ = LINK_DIST * LINK_DIST;
    const MOUSE_RAD_SQ = MOUSE_RAD * MOUSE_RAD;
    const PUSH_RAD_SQ = PUSH_RAD * PUSH_RAD;

    let last = 0;
    const FRAME_INTERVAL = 1000 / 60;
    let isVisible = true;

    // IntersectionObserver to stop animation when not in view
    const io = new IntersectionObserver((entries) => {
      isVisible = entries[0].isIntersecting;
      if (isVisible) animate();
    }, { threshold: 0.1 });
    io.observe(canvas);

    const animate = (now = 0) => {
      if (!isVisible) return;
      if (now - last < FRAME_INTERVAL) { animFrame = requestAnimationFrame(animate); return; }
      last = now;
      ctx.clearRect(0, 0, width, height);

      const mx = mouse.x, my = mouse.y;
      const cellSize = LINK_DIST;
      const cols = Math.ceil(width / cellSize);
      const rows = Math.ceil(height / cellSize);
      const grid: Particle[][] = [];

      // Physics update + spatial grid build
      for (const p of particles) {
        const dx = mx - p.x, dy = my - p.y;
        const dSq = dx * dx + dy * dy;
        if (dSq < PUSH_RAD_SQ && dSq > 0) {
          const d = Math.sqrt(dSq);
          const force = (PUSH_RAD - d) / PUSH_RAD * 0.01;
          p.vx += (dx / d) * force;
          p.vy += (dy / d) * force;
          p.near = true;
        } else {
          p.near = false;
        }
        p.vx += (Math.random() - 0.5) * 0.002;
        p.vy += (Math.random() - 0.5) * 0.002;
        p.vx *= 0.995; p.vy *= 0.995;
        p.x += p.vx; p.y += p.vy;
        if (p.x < 0) p.x = width;
        if (p.x > width) p.x = 0;
        if (p.y < 0) p.y = height;
        if (p.y > height) p.y = 0;

        const col = (p.x / cellSize) | 0;
        const row = (p.y / cellSize) | 0;
        const idx = row * cols + col;
        if (idx >= 0 && idx < rows * cols) {
          if (!grid[idx]) grid[idx] = [];
          grid[idx].push(p);
        }
      }

      const rgb = dark ? '255,255,255' : '60,60,60';

      // Batch draw: normal particles (single fill call)
      ctx.fillStyle = `rgba(${rgb},0.35)`;
      ctx.beginPath();
      for (const p of particles) {
        if (!p.near) { ctx.moveTo(p.x + p.size, p.y); ctx.arc(p.x, p.y, p.size, 0, Math.PI * 2); }
      }
      ctx.fill();

      // Batch draw: near-mouse particles (single fill call)
      ctx.fillStyle = `rgba(${rgb},0.7)`;
      ctx.beginPath();
      for (const p of particles) {
        if (p.near) { ctx.moveTo(p.x + p.size, p.y); ctx.arc(p.x, p.y, p.size, 0, Math.PI * 2); }
      }
      ctx.fill();

      // Batch draw: all connection lines (single stroke call)
      ctx.strokeStyle = `rgba(${rgb},0.15)`;
      ctx.lineWidth = 0.8;
      ctx.beginPath();
      for (const p1 of particles) {
        const dxM = p1.x - mx, dyM = p1.y - my;
        if (dxM * dxM + dyM * dyM > MOUSE_RAD_SQ) continue;
        const col = (p1.x / cellSize) | 0;
        const row = (p1.y / cellSize) | 0;
        for (let r = row - 1; r <= row + 1; r++) {
          if (r < 0 || r >= rows) continue;
          for (let c = col - 1; c <= col + 1; c++) {
            if (c < 0 || c >= cols) continue;
            const cell = grid[r * cols + c];
            if (!cell) continue;
            for (const p2 of cell) {
              if (p1 === p2) continue;
              const dx = p1.x - p2.x, dy = p1.y - p2.y;
              if (dx * dx + dy * dy < LINK_DIST_SQ) {
                ctx.moveTo(p1.x, p1.y);
                ctx.lineTo(p2.x, p2.y);
              }
            }
          }
        }
      }
      ctx.stroke();

      animFrame = requestAnimationFrame(animate);
    };

    return () => {
      mo.disconnect();
      io.disconnect();
      window.removeEventListener('resize', resize);
      window.removeEventListener('mousemove', handleMouseMove);
      window.removeEventListener('touchmove', handleTouchMove);
      cancelAnimationFrame(animFrame);
    };
  });
</script>

<canvas
  bind:this={canvas}
  class="absolute inset-0 pointer-events-none"
  style="z-index: 2; background: transparent; will-change: transform;"
></canvas>
